name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      COREPACK_INTEGRITY_KEYS: 0
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v5
      - name: Get pnpm version
        run: echo "PNPM_VERSION=$(cat package.json | jq .volta.pnpm)" >> "$GITHUB_ENV"
      - name: Enable pnpm with corepack
        run: corepack enable && corepack prepare pnpm@${{env.PNPM_VERSION}} --activate 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'
          cache: pnpm
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
      - name: Build
        run: pnpm build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
